export { createSeasonSnapshot } from "./domain/seasonMaterializer.js";
export { entityVisibilityState, isEntityF1EligibleInSeason, isEntityTalentVisibleInSeason, isEntityVisibleInSeason, listVisibleDrivers, listVisibleSponsors, listVisibleStaff, listVisibleTeams, normalizeEntityVisibility } from "./domain/entityVisibility.js";
export { getSeasonReadiness, listSupportedSeasons, loadHistoricalSeason } from "./domain/historicalWorld.js";
export { createSeasonDatabasePayload, loadSeasonDatabasePayload, mergeSeasonBoundaryReferences, SEASON_DATABASE_FORMAT, SEASON_DATABASE_SCHEMA_VERSION, validateSeasonDatabasePayload } from "./data/seasonDatabase.js";
export { createCareerFromSeasonDatabase, validateSeasonDatabaseAgainstGlobal } from "./data/careerBootstrap.js";
export { DeveloperPlaytestSession, listDeveloperPlaytestTeams } from "./app/developerPlaytest.js";
export { developerApplyManagerJob, developerArchiveInboxItem, developerBoard, developerCommercial, developerContractNegotiations, developerInbox, developerManagementOverview, developerManagerCareer, developerMarkInboxRead, developerMarket, developerOpenDriverNegotiation, developerOpenSponsorNegotiation, developerOpenStaffNegotiation, developerPeople, developerRecruitment, developerResolveInboxDecision, developerResolveSponsorActivity, developerResponsibilities, developerSetResponsibility, developerSetShortlist, developerStaffContractNegotiations, developerStaffRecruitment, developerStartScouting, developerSubmitBoardRequest, developerSubmitDriverOffer, developerSubmitSponsorOffer, developerSubmitStaffOffer, developerWithdrawDriverNegotiation, developerWithdrawSponsorNegotiation, developerWithdrawStaffNegotiation } from "./app/managementPlaytest.js";
export { developerCastGovernanceVote, developerGovernance, developerRebrandControlledTeam } from "./app/governancePlaytest.js";
export { loadSeasonPackPayload, parseSeasonPackPayload, seasonPackSheetRows, SeasonPackValidationError, validateSeasonPackPayload } from "./data/seasonPackLoader.js";
export { applySeasonPackOverlay, overlaySourceChecksum, SeasonPackOverlayError } from "./data/seasonPackOverlay.js";
export { loadSeasonPackRuntimePayload, validateSeasonPackRuntimePayload } from "./data/seasonPackRuntime.js";
export { createSaveWorld } from "./save/createSaveWorld.js";
export { deserializeSaveWorld, SAVE_FORMAT, SAVE_SCHEMA_VERSION, serializeSaveWorld } from "./save/serialization.js";
export { addManagementInboxItem, archiveManagementInboxItem, ensureManagementInbox, listManagementInbox, managementInboxSummary, markManagementInboxRead, resolveManagementInboxDecision } from "./game/management/inbox.js";
export { buildDriverScoutingReport, completeDriverScoutingAssignment, driverScoutingKnowledge, ensureScoutingState, listRecruitmentCandidates, SCOUTING_EVENT, scoutingSummary, setDriverShortlist, startDriverScoutingAssignment } from "./game/management/scouting.js";
export { acceptDriverContractCounterEvent, CONTRACT_NEGOTIATION_EVENT, contractNegotiationSummary, ensureContractNegotiationState, evaluateDriverContractOffer, listContractNegotiations, openDriverContractNegotiation, submitDriverContractOfferEvent, transferCompensationRequirement, withdrawDriverContractNegotiationEvent } from "./game/management/contracts.js";
export { activeCompetingOffers, adjustRelationship, ensurePeopleState, ensurePersonState, ensureRelationship, ensureRepresentative, evaluateDriverTransferInterest, peopleSummary, personProfile, personProjection } from "./game/management/people.js";
export { chooseRivalTeam, createExternalDriverOffer, expireExternalOffers, listOpenExternalOffers, marketPressureForDriver, marketSummary } from "./game/management/market.js";
export { boardProjection, boardStatus, ensureBoardState, evaluateBoard, initializeBoardTeam, resolveBoardRequest, submitBoardRequest } from "./game/management/board.js";
export { acceptManagerJobOfferEvent, adjustManagerReputation, appointManager, createManagerJobOffer, decideManagerApplication, dismissManager, ensureManagerCareer, listManagerJobVacancies, MANAGER_EVENT, managerCareerProjection, submitManagerApplicationEvent } from "./game/management/managerCareer.js";
export { ensureResponsibilities, responsibilityAreas, responsibilityOwner, responsibilityProjection, setResponsibility } from "./game/management/responsibilities.js";
export { acceptStaffCounterEvent, buildStaffCounterTerms, evaluateStaffInterest, evaluateStaffOffer, listStaffContractNegotiations, listStaffRecruitmentCandidates, openStaffContractNegotiation, STAFF_NEGOTIATION_EVENT, staffRecruitmentSummary, submitStaffContractOfferEvent, withdrawStaffNegotiationEvent } from "./game/management/staffRecruitment.js";
export { acceptSponsorCounterEvent, activateSponsorDeal, calculateTeamMarketability, COMMERCIAL_EVENT, commercialEraProfile, commercialMonthlySponsorIncome, commercialProjection, commercialSummary, createSponsorActivity, driverMarketability, ensureCommercialState, evaluateSponsorInterest, expectedSponsorTerms, expireCommercialDeals, initializeCommercialTeam, initializeCommercialWorld, listSponsorMarket, listSponsorNegotiations, openSponsorNegotiation, raceCommercialConsequences, resolveSponsorActivity, submitSponsorOfferEvent, updateCommercialMarketability, withdrawSponsorNegotiationEvent } from "./game/management/commercial.js";
export { TECHNICAL_COMPONENTS, TECHNICAL_EVENT, advanceTechnicalMonth, ensureTechnicalTeam, ensureTechnicalWorld, fitComponentSpec, initializeTechnicalWorld, releaseNextSeasonSpecifications, startFacilityUpgrade, startManufacturingJob, startTechnicalDesignProject, technicalCarComponentsForDriver, technicalFacilityMaintenanceAnnual, technicalProjection, technicalSummary } from "./game/management/technical.js";
export { SUPPLIER_EVENT, acceptSupplierCounter, activateSupplierSeason, activeEngineForTeam, activeSupplierContract, engineById, engineCatalog, ensureSupplierTeam, expectedSupplierTerms, initializeSupplierWorld, listSupplierMarket, openSupplierNegotiation, submitSupplierOffer, supplierInterest, supplierProjection, technicalSupplierMonthlyCost, withdrawSupplierNegotiation } from "./game/management/suppliers.js";
export { RELIABILITY_EVENT, adjustReliabilityForCondition, applyRaceWear, conditionForDriver, conditionPerformanceModifier, ensureReliabilityTeam, fittedComponentReturnable, initializeReliabilityWorld, rebuildFittedComponent, registerFittedComponentUnit, reliabilityProjection, replaceWornComponent, serviceEngineUnit } from "./game/management/reliability.js";
export { PRESEASON_EVENT, ensurePreseasonTeam, initializePreseasonWorld, isPreseasonWindow, preseasonDevelopmentBonus, preseasonProjection, runPreseasonTest } from "./game/management/preseason.js";
export { REGULATION_EVENT, applyEnactedRegulations, castRegulationVote, ensureRegulationState, initializeRegulationState, listRegulationProposals, openHistoricalReferenceProposal, openRegulationProposal, regulationEraProfile, regulationPackage, regulationProjection, regulationVoteSummary, resolveRegulationProposal } from "./game/management/regulations.js";
export { applyTechnicalRegulationTransition } from "./game/management/regulationImpact.js";
export { TEAM_EVOLUTION_EVENT, activateAcceptedTeamEntry, decideTeamEntryApplication, ensureTeamEvolutionState, exitTeam, initializeTeamEvolutionState, listTeamEntryCandidates, rebrandTeam, submitTeamEntryApplication, teamEvolutionProjection, updateTeamDistress } from "./game/management/teamEvolution.js";
export { createRng } from "./sim/random.js";
export { availableTyreCompounds, createRaceStrategyPlan, evaluateRaceStrategy } from "./sim/raceStrategy.js";
export { currentStrategyStint, reviseRaceStrategy, reviseStartingTyreCompound, selectLiveTyreCompound } from "./sim/liveStrategy.js";
export { evaluateAiLiveStrategyDecision, isAiManagedStrategy, listAiLiveStrategyDecisions } from "./sim/aiLiveStrategy.js";
export { advanceLiveRaceSession, applyLiveStrategyInstruction, applyPreRaceStartingTyre, clearCompletedLiveRaceSession, getLiveRaceSession, recommendLiveStrategyInstruction, startLiveRaceSession } from "./sim/liveRaceController.js";
export { createRaceStartBaseline } from "./sim/raceStartBaseline.js";
export { adjustWeekendSetup, setupFields } from "./sim/weekendSetup.js";
export { activeDamagePaceLoss, repairDamageAtPit, resolveDamagePolicy, resolveIncidentDamage } from "./sim/damageModel.js";
export { advanceTyreThermalState, completeTyreThermalLap, resolveTyreDynamicTraits } from "./sim/tyreDynamics.js";
export { resolveTrackEvolutionModel, trackEvolutionAt } from "./sim/trackDynamics.js";
export { decideLiveRaceControl, incidentSeverity, resolveRaceControlPolicy, reviewRaceTimeline } from "./sim/raceControl.js";
export { resolveSectorModel, sectorPaceModifier, selectIncidentSector } from "./sim/sectorModel.js";
export { simulateTemporalRace } from "./sim/raceTimeline.js";
export { advanceDay } from "./sim/clock.js";
export { advanceDays, dispatchSimulationEvents, initializeSimulation, SIM_EVENT } from "./sim/timeEngine.js";
export { runHeadlessSimulation } from "./sim/headless.js";
export { runLongRunValidation, validateLongRunWorld } from "./sim/validation/longRun.js";
export { CONTRACT_EVENT, createContractMilestoneSystem } from "./sim/systems/contractMilestones.js";
export { ENTITY_EVENT, createEntityAvailabilitySystem } from "./sim/systems/entityAvailability.js";
export { ageOnDate, CAREER_EVENT, createCareerLifecycleSystem } from "./sim/systems/careerLifecycle.js";
export { createCareerDevelopmentSystem } from "./sim/systems/careerDevelopment.js";
export { createRetirementSystem, retirementProbability } from "./sim/systems/retirement.js";
export { createRetirementEmploymentSystem } from "./sim/systems/retirementEmployment.js";
export { EMPLOYMENT_EVENT, createAiEmploymentDecisionSystem, createEmploymentMarketSystem } from "./sim/systems/employmentMarket.js";
export { createTransferVacancySystem } from "./sim/systems/transferVacancy.js";
export { PEOPLE_EVENT, createPeopleDynamicsSystem } from "./sim/systems/peopleDynamics.js";
export { createScoutingManagementSystem } from "./sim/systems/scoutingManagement.js";
export { createContractNegotiationSystem } from "./sim/systems/contractNegotiation.js";
export { createStaffNegotiationSystem } from "./sim/systems/staffNegotiation.js";
export { MARKET_EVENT, createMarketDynamicsSystem } from "./sim/systems/marketDynamics.js";
export { BOARD_EVENT, createBoardManagementSystem } from "./sim/systems/boardManagement.js";
export { createManagerCareerSystem } from "./sim/systems/managerCareer.js";
export { STAFF_ADVICE_EVENT, createStaffAdviceSystem } from "./sim/systems/staffAdvice.js";
export { createCommercialManagementSystem } from "./sim/systems/commercialManagement.js";
export { createCommercialInboxSystem } from "./sim/systems/commercialInbox.js";
export { createTechnicalInboxSystem } from "./sim/systems/technicalInbox.js";
export { createTechnicalReliabilitySystem } from "./sim/systems/technicalReliability.js";
export { createGovernanceManagementSystem } from "./sim/systems/governanceManagement.js";
export { createGovernanceInboxSystem } from "./sim/systems/governanceInbox.js";
export { archiveExitedTeamOperationalState, createTeamExitCleanupSystem } from "./sim/systems/teamExitCleanup.js";
export { createManagementInboxSystem } from "./sim/systems/managementInbox.js";
export { RACE_ENTRY_EVENT, createRaceEntrySystem } from "./sim/systems/raceEntry.js";
export { TEAM_FINANCE_EVENT, createTeamEconomySystem } from "./sim/systems/teamEconomy.js";
export { TEAM_DEVELOPMENT_EVENT, createTeamDevelopmentSystem } from "./sim/systems/teamDevelopment.js";
export { SEASON_EVENT, createSeasonRolloverSystem } from "./sim/systems/seasonRollover.js";
export { STRATEGY_EVENT, createRaceStrategySystem } from "./sim/systems/raceStrategy.js";
export { PERFORMANCE_CALIBRATION_EVENT, calibratedCarComponents, calibrateTyreStrategies, createPerformanceCalibrationSystem } from "./sim/systems/performanceCalibration.js";
export { RACE_EVENT, createRaceWeekendSystem } from "./sim/systems/raceWeekend.js";
export { RACE_TIMELINE_EVENT, createRaceTimelineSystem } from "./sim/systems/raceTimeline.js";
export { RACE_CONTROL_EVENT, createRaceControlSystem } from "./sim/systems/raceControl.js";
export { CHAMPIONSHIP_EVENT, createChampionshipSystem, parsePointsSystem } from "./sim/systems/championship.js";
export { createCoreWorldSystems } from "./sim/systems/coreWorldSystems.js";